### PR TITLE
Recursive

### PR DESCRIPTION
**Pull request by romancandlethoughts**
Added ability to recursively iterate through a codebase looking for README.md files and adding them as relative links to the ToC

### CODE REVIEW

**Comment by nickyout** [comment]
Interesting. I'll test it when I have the time. At first glance it seems like you took backwards compatibility into consideration, which I like.

**Comment by romancandlethoughts** [comment]
Awesome! thanks!

**Comment by nickyout** [comment]
Checked it. I think it's useful; I remember wanting a feature like this in another project. I like the granularity and defaults of the options, I think they're sane. 

Points of attention:

* Currently only works when the target md file is in the repo root directory. I tried `./test/README.md` and upon clicking on the generated links it did `./test/test/...` on all the links. So if I would like to have that tree inside `./doc` or `./wiki` it would not work. I think that's a shame. Willing to resolve that?
* I hope you're willing to add an explanation of the new options to the repo's `README.md`. Undocumented features are no features imo. 

Nitpick:

* I saw you using `/README.md/` as regexp, but I don't think you intend the dot to match any character the way that it will do now. I doubt anybody would ever notice it in practice, though.

**Comment by romancandlethoughts** [comment]
Absolutely!

• I will just need to prepend the path set in `recuriveRootDir` to the output relative paths.

• I will absolutely update the docs. I love docs. I wanted to make sure this had a chance at being integrated before writing anything. I will include them in the next commit.

Nitpick:
• Nice catch. That `.` will be escaped -- though, I am still wondering if we should be matching `/.*\.md/g` instead of `/README\.md/`-- What are your thoughts?

**Comment by nickyout** [comment]
Cool.

Personally I like the current setting, targeting `README.md` only. But that's because I imagine myself setting `README.md` files in certain directories that contain a single feature of a greater application, and possibly refer further to a specific md inside that README. However, I've seen some repos using a separate `docs` directory. I think it depends on the use case. 

Another way to fly at it is to make the whole thing customizable. Instead of specifying a root folder for recursiveDirRoot, you could specify a glob pattern. Grunt comes with glob expand natively anyway ([link](http://gruntjs.com/api/grunt.file#grunt.file.expand)). I'm reading it accepts both array and string, and normalizes it into an array of unique file paths. With that, you leave the selection of `.md` files entirely up to the user. They could specify an array of specific files if they wanted to, maybe even non-`.md` files?

**Comment by romancandlethoughts** [comment]
hmm. I like the idea of including non-`.md`, but I think it may be feature overkill. That functionality is almost available currently (if you set values for the `excludedDirs` option). I realize you can't target specific files this way, but I think the use cases for specific file targeting (that wouldn't be practically identical to directory excluding) are few and far between.

I will make `README.md` the default value for matching, but will add an option to match any `.md` file.

**Comment by nickyout** [comment]
I can't shake the feeling that globbing would be more elegant. I'm now willing to do the work required to incorporate it, but I'm still interested in why you think it would be the worse solution. Let me expand upon my opinion.

The globbing solution is already present in grunt, and supports including several paths, a single globbing path, excluding paths and combinations ((link)[https://github.com/isaacs/node-glob#glob-primer]). I've used it in several contexts (in grunt, vim, a subset in git), which gives me the impression it's a bit of a standard rather than it being something exotic. It supports *all* use cases described:

* Target `README.md` recursively: `**/README.md`
* Target any `md` recursively: `**/*.md`
* Target any `md` except those in `./doc`: `["**/*.md", "!doc/**"]`
* Target specific files: `["doc/README.md", "doc/nest/LICENSE", ... ]`

All of this within a single parameter. The fact that you can target specific files including non-`md` files is merely a side effect of the flexibility of globbing. 

You're currently using three parameters to describe the same thing: `recursiveDirRoot`, `excludedDirs`, `matchAllMd`. Furthermore, and I'm sorry I did not notice this before, the pattern `/README\.md/` will still match with `_README.md` or `.README.md` unless it becomes `/^README\.md$/` or whatever node-dir expects I suppose. It just seems easier to me to leave all that file selecting to the user, by simply exposing a globbing parameter.

**Comment by romancandlethoughts** [comment]
I agree with you that the use of globbing would be a more elegant solution. I wasn't taking into consideration the flexibility of globbing patterns (as you mentioned above, the individual file selection is just a "side-effect" of globbing). Not only is it less confusing for the user to config, it would probably result in less code as well. Would you mind tagging me in whatever you push up?

**Comment by nickyout** [comment]
So, not sure in which ways I can actually 'tag' you in this commit, but I'm sure this should work.

@romancandlethoughts check: https://github.com/nickyout/grunt-doctoc/tree/recursive

This is what I came up with. `listFiles` as trigger and path. `listFilesHeader` as its header. I think it covers its functionality better than `recursive`. I also noticed that some plugins started to choke on dashes inbetween file names when they were used as links, so I escaped them (`_` to `\_`). Though I think Github md already ignores inbetween dashes. 

What do you think?

**Comment by romancandlethoughts** [comment]
@nickyout great! I am checking out your recursive branch now.  I think conflating the trigger and the path is good. I think it would be rare that someone would want to set up grunt-doctoc in a root without a README.

**Pull request closed without merging**
